--1-)

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS MONTH FROM HR.EMPLOYEES;
/
--2-)

SELECT DISTINCT JOB_ID AS JOB , DECODE(JOB_ID,'AD_PRES','A',
                                              'ST_MAN','B',
                                              'IT_PROG','C',
                                              'SA_REP','D',
                                              'ST_CLERK','E', 
                                               0)
AS GRADE FROM HR.EMPLOYEES ORDER BY GRADE;
/
--3-)

SELECT DISTINCT JOB_ID,
CASE 
    WHEN JOB_ID = 'AD_PRES'  THEN 'A'
    WHEN JOB_ID = 'ST_MAN'   THEN 'B'
    WHEN JOB_ID = 'IT_PROG'  THEN 'C'
    WHEN JOB_ID = 'SA_REP'   THEN 'D'
    WHEN JOB_ID = 'ST_CLERK' THEN 'E'
    ELSE '0'
END AS GRADE
FROM HR.EMPLOYEES
ORDER BY GRADE;
/
--4-)

SELECT EMPLOYEE_ID, LAST_NAME FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM HR.EMPLOYEES WHERE LAST_NAME LIKE '%i%') ORDER BY EMPLOYEE_ID;
/
--5-)

CREATE TABLE MY_EMP_TABLE(
  ID NUMBER NOT NULL PRIMARY KEY,
  LAST_NAME VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  SALARY NUMBER
);

INSERT INTO MY_EMP_TABLE VALUES (1,'Black', 'John', 1100);
INSERT INTO MY_EMP_TABLE VALUES (2,'White', 'Kent', 1300);
INSERT INTO MY_EMP_TABLE VALUES (3,'Orange', 'David', 1700);
INSERT INTO MY_EMP_TABLE VALUES (4,'Pink', 'Alissa', 1900);

UPDATE MY_EMP_TABLE SET SALARY=SALARY*(1.10);

DELETE FROM MY_EMP_TABLE WHERE FIRST_NAME = 'David'; 

TRUNCATE TABLE MY_EMP_TABLE;
/
